# Site settings
title: The Trip
email: deanmvizer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deanmv.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: :compressed